### ISSUE TITLE
A way to delete saved warscrolls

### ISSUE THREAD

**Issue by Mystic-Fox** [PeteAUK/warscroll-designer#10] opened 2023-04-26 00:21 UTC
**Is your feature request related to a problem? Please describe.**
Related to the issue I had with loading old scrolls, I now have a bunch of scrolls that are just Test2

**Describe the solution you'd like**
A button someplace to clear a warscroll you don't want from the library

**Comment by PeteAUK** [comment] 2023-04-26 06:22
Duplicate of #7

**Comment by PeteAUK** [comment] 2023-04-26 06:23
The delete function will form part of the "Library" functionality as per the #7 suggestion :)

**Closed as completed by PeteAUK** 2023-04-26 06:23 UTC
