### ISSUE TITLE
Warscrolls not actually saving to account

### ISSUE THREAD

**Issue by TheOccultNerd** [PeteAUK/warscroll-designer#14] opened 2023-05-10 23:33 UTC
**Describe the bug**
After finishing a scroll and clicking the save icon, it first pops up in the list as undefined, then once save is pressed again the name is correct. however the scroll is not present in the list of created warscolls when the page is re-opened and sign in is complete 

**To Reproduce**
create a warscroll, name it, save, save again and return to the page in a new tab.

**Expected behaviour**
being able to access scrolls previously made and saved.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 112.0.5615.138

**Comment by PeteAUK** [comment] 2023-05-11 06:34
I suspect this is a duplicate of #13.  Could you confirm the following:

* Are you logged in with Google
* Do you have any warscrolls already saved

I'm struggling to replicate this happening on any machine even when running in incognito mode, so I'm either missing a step or doing something automatically that means the issue doesn't appear 😊

**Comment by TheOccultNerd** [comment] 2023-05-11 15:25
Oh sorry if I didnt explain well, I was logged in with google and I do have warscrolls that were saved in the previous version that I can edit and it does properly save those, I just cant save new scrolls.

**Comment by exonian** [comment] 2023-05-11 18:37
I get this on all devices, across two google accounts (neither with anything saved, but one set up specially for the occasion to test it wasn't just my account 😅)

**Comment by PeteAUK** [comment] 2023-05-12 08:22
I'll try and have another punt this weekend at working out what's going on.  Have tried on multiple machines and not encountered it yet, so I'm not quite sure what's happening.  Initial feeling was browser caching, but I think that's a red herring in truth.

**Comment by PeteAUK** [comment] 2023-05-13 10:58
Blimey that was a bit awkward!  However I believe that I've now solved this.  Basically it was two problems rather than one which also didn't exist on my local set up.  Please test this out and let me know how it goes.

**Comment by exonian** [comment] 2023-05-13 11:05
@PeteAUK It works!

**Comment by exonian** [comment] 2023-05-13 11:14
I may have spoken too soon... 😬 Having trouble getting a second scroll to save. Trying to characterise it now.

**Comment by PeteAUK** [comment] 2023-05-13 11:20
I have just noticed that you can't select a newly saved warscroll - event handlers not attaching!

**Comment by exonian** [comment] 2023-05-13 11:29
I think I'm having trouble saving at any point after hitting "new", even with refreshes after save events. I'm not sure if there's a little more to it than that, but "save, refresh, enter name, tab, save, refresh, enter name, tab, save" seems to work fine, but I think it's hitting "new" where my problems start. Maybe.

**Comment by PeteAUK** [comment] 2023-05-13 11:30
Ah, worked it out - was the same issue you were having.  When clicking "new" the `loaded` variable wasn't enumerating to empty.  I've just modified this and seems to be OK now.

**Comment by exonian** [comment] 2023-05-13 11:31
Ah perfect. That'll presumably solve another issue I saw a few minutes ago 🎉 (new scrolls saving as local if you'd loaded up a local scroll before hitting "new")

**Comment by PeteAUK** [comment] 2023-05-13 11:31
It should do with luck!  But happy to reinvestigate if you're still having problems :)

**Comment by exonian** [comment] 2023-05-13 11:34
Nah I'm happy to test that case and report back if it's still there. And also the one I mentioned the other day about being able to save with no warscroll name: I think potentially this stops that too? Cos it was directly after hitting new, and I imagine it not unloading properly may have been what was making the diff false-positive

But yes, as for this ticket I was just about to write here "oh wait scratch that I don't think it's the 'new' thing after all!" but it turned out you'd just fixed it 😂

**Comment by PeteAUK** [comment] 2023-05-13 11:53
Cheers.  The saving with no name I've got on the short list to sort out - there's a "have I changed" flag that isn't resetting for some reason, however it that should really be a mandatory field too.

**Closed as completed by PeteAUK** 2023-05-13 11:53 UTC
Labels: bug, accepted
